version: '3'

services:
  backend:
    build: 
      context: backend
    image: node-test
    container_name: backend
    networks:
      - test-network
    tty: true
    ports:
      - "3001:3000"
    
  nginx:
    build: 
      context: frontend
    image: nginx-test
    container_name: nginx
    networks:
      - test-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - backend

networks:
  test-network:
    driver: bridge